### PR TITLE
General Tweaks and Fixes

### PR DESCRIPTION
**Pull request by bauen1**
fix: compiling under 511 tgstation/tgstation/pull/19306
tweak: config files to fit fallout
tweak: terminal icon during construction
del: junk in /data that shouldn't be there

### CODE REVIEW

**Comment by SpyderVenom** [comment]
I have an error when I try to compile the source code file with the latest edited 14 days ago files... Dont suppose a new source zip can be put together?

**Comment by bauen1** [comment]
Huh i'm a 100% sure this compiled, can you try to compile with a clean install ? (don't have time right now)

**Comment by SpyderVenom** [comment]
When I compile I get...

loading fallout13.dme
fallout13.dme:5:error: missing left-hand argument to <.
fallout13.dmb - 1 error, 0 warnings (10/26/16 12:13 am)


Im guessing its something simple but I am not a coder, Im a networker... heh

**Comment by SpyderVenom** [comment]
Erm and...

loading fallout13.dme
loading interface\skin.dmf
code\modules\admin\verbs\fps.dm:2:error: fps: duplicate definition (conflicts with built-in proc)
fallout13.dmb - 1 error, 0 warnings (10/26/16 12:37 am)

**Comment by bauen1** [comment]
Not sure since you deleted you messages but the <<<<<<< HEAD and >>>>>> stuff are used by git so you can resolve merge conflicts

**Comment by SpyderVenom** [comment]
I managed to get it to compile, thanks much! 

Sent from Yahoo Mail on Android 

  On Wed, Oct 26, 2016 at 9:32 AM, bauen1notifications@github.com wrote:  
Not sure since you deleted you messages but the <<<<<<< HEAD and >>>>>> stuff are used by git so you can resolve merge conflicts

**Pull request merged**
